apiVersion: v1
kind: Pod
metadata:
     name: cipod
     namespace: meesho
     labels:
        app: cipod
spec: 
   containers:
       - image: nginx:latest
         ports: 
           - containerport: 80
         name: nginxcont

---
apiVersion: v1
kind: Service
metadata:
   name: ciservice
   namespace: meesho
spec:
  selector:
    app: cipod
  type: ClusterIP
  ports:
    - port: 80
      targetport: 80

protocol: TCP