apiVersion: apps/v1
kind: DaemonSet
metadata:
     name: awagent
     labels:
        app: awagent
spec:
   selector:
      matchLabels:
         app: awagent
   template:
     metadata:
      name: awagent
      labels:
        app: awagent
     spec:
       containers:
         - name: nginx
           image : nginx
           ports:
            - containerPort: 80

               
